---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloud-discovery-helmrelease
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: chart
      version: '0.1.1'
      sourceRef:
        kind: GitRepository
        name: podinfo
        namespace: flux-system
      interval: 2m

