---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: aggr
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:3.1.1-debian-9-*
spec:
  releaseName: ghost
  chart:
    git: git@github.com:moredatta/aggrigation-flask.git
    ref: master
    path: /flux
 
